alias rm='/bin/rm -i'
alias gc='git commit -m'
alias gs='git status -sb'
alias ga='git add -p'
alias proxy='ssh -D 2001 -Nf mike-burns.com'
alias venv='source venv/bin/activate'
alias sass_watch='sass --watch sass:. --style compressed'
