#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
$(rbenv which ripper-tags) --tag-relative -R -f"$dir/$$.tags" .
mv "$dir/$$.tags" "$dir/tags"
